#!/bin/bash
 
clear

# djBB Buildbox
echo
echo
echo
echo

echo "Set up buildbox, linux android build environment" 
echo "|--------------------------------------|"
echo "|--------------------------------------|"
echo "|-- ++ --  @dj8218521 Twitter --- ++ --|"
echo "|-- ++ --  @dj8218521 Github  --- ++ --|"
echo "|--------------------------------------|"
echo "|--------------------------------------|"
sleep 3
echo
echo "I used Ubuntu Linux 12.04"
sleep 3
read -p "Are you ready to get started? (y/n) " RESP
if [ "$RESP" = "y" ]; then
  echo "OK, GOOD."
else
  echo "Ok come back when you're ready! Thanks for downloading, hit thanks if you do not mind."
sleep 2
exit
fi
sleep 1
echo "This will take a few minutes and you will need to press the Y key for 'yes' to continue, pay attention to that."
sleep 2
echo "Let's get started ..."
sleep 1
sudo apt-get install ubuntu-restricted-extras
sudo wget --output-document=/etc/apt/sources.list.d/medibuntu.list http://www.medibuntu.org/sources.list.d/$(lsb_release -cs).list && sudo apt-get --quiet update && sudo apt-get --yes --quiet --allow-unauthenticated install medibuntu-keyring && sudo apt-get --quiet update
sudo apt-get install libdvdcss2
sudo apt-get install openjdk-6-jdk
sudo apt-get install python
sudo apt-get install git-core
sleep 1

#adding these files to test my git push
#test1
#test2
#test done
sleep 2
echo "You will see a gray screen with purple background, hit tab then spacebar"
sleep 2
read -p "Are you still with me? (y/n) " RESP
if [ "$RESP" = "y" ]; then
  echo "OK, GOOD."
else
  echo "Ok come back when you're ready! Thanks for downloading, hit thanks if you do not mind."
sleep 2
exit
fi

sleep 1
wget http://www.broodplank.net/51-android.rules
sudo mv -f 51-android.rules /etc/udev/rules.d/51-android.rules
sudo chmod 644 /etc/udev/rules.d/51-android.rules
sleep 1
wget http://dl.google.com/android/adt/adt-bundle-linux-x86_64-20131030.zip
mkdir ~/adt-bundle
mv adt-bundle-linux-x86_64-20131030.zip ~/adt-bundle/adt_x64.zip
cd ~/adt-bundle
unzip adt_x64.zip
mv -f adt-bundle-linux-x86_64-20131030/* .
echo "Configuring environment"
echo -e '\n# Android tools\nexport PATH=${PATH}:~/adt-bundle/sdk/tools\nexport PATH=$
echo -e '\nPATH="$HOME/adt-bundle/sdk/tools:$HOME/adt-bundle/sdk/platform-tools:$PAT$
echo "Placing desktop shortcuts"
ln -s ~/adt-bundle/eclipse/eclipse ~/Desktop/Eclipse
ln -s ~/adt-bundle/sdk/tools/android ~/Desktop/SDK-Manager
sleep 1

sudo apt-get install android-tools-adb
sudo apt-get install curl

echo "Here is VLC Media Player also"
sudo apt-get install vlc
sleep 1
clear

echo "Now, everything is done. Just reboot the machine to finsh"
